name: Build BeagleBone Black Image with Tester

on:
  push:
    branches:
      - buildroot-flow
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Buildroot
      uses: actions/checkout@v4
      with:
        
        repository: 'buildroot/buildroot'
        ref: '2024.05.2'
        path: 'buildroot'

    - name: Checkout beagle-tester
      uses: actions/checkout@v4
      with:
        repository: 'VidhuSarwal/beagle-tester'
        path: 'buildroot/package/beagle-tester'

    - name: Install Buildroot dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libncurses5-dev cpio

    - name: Configure and Build for BeagleBone Black
      working-directory: ./buildroot
      run: |
        make beaglebone_defconfig
        
        echo "BR2_PACKAGE_BEAGLE_TESTER=y" >> .config
        
        make olddefconfig

        echo "Starting Buildroot make..."
        make

    - name: Upload Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: beaglebone-black-image
        path: buildroot/output/images/sdcard.img
